name: Sync Releases from Microsoft WSL

on:
  workflow_dispatch:                           # 手动触发
  schedule:
    - cron: "0 */12 * * *"                    # 每 12 小时自动运行（UTC 0:00 和 12:00）

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          src_repo: microsoft/WSL
          copy_assets: true
