name: Sync Releases from Microsoft WSL

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Releases
        uses: andrewthetechie/gha-clone-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          src_repo: microsoft/WSL
          copy_assets: true
